Doctype-specific self-closing tags
textile/php-textile pull request #221
Opened 2022-12-03 11:04 UTC by jools-r

Currently Textile outputs self-closing tags such as `<br />` and `<img … />` tags using the trailing slash regardless of the doctype that is set. This is now flagged as an error by the W3C validator for the HTML5 doctype.

This mini-PR outputs self-closing (void) tags according to the doctype set:

- for XHTML: `<br />` and `<img … />` etc.
- for HTML5: `<br>` and `<img …>` etc.

### Type of change

- [x] Bug fix – just typos and consistent quotes
- [x] New feature
- [?] Breaking change
- [ ] Security fix

### Description

- New internal `getLineBreak()` function replaces hard-coded `<br />` instances.
- In the existing `newTag()` function, the self-closing ` />` syntax is only passed to Netcarver/Textile/Tag() when the doctype is not html5. This is a simpler solution than passing through the doctype as an attribute of Netcarver/Textile/Tag().

Other changes
- Minor typos in the descriptions and one quote inconsistency (in a separate commit)

Whether this is a breaking change is debatable. For existing XHTML doctype documents (which is still the default setting), the output is unchanged. For HTML5 doctypes the output is now different – but correct according to the validator – to how it was before. The output in the browser is unchanged.

### Checklist

- [x] I documented my additions and changes using PHPdoc.
- [ ] I wrote fixtures to cover my additions.
- [ ] `$ composer update`
- [ ] `$ composer test`
- [ ] `$ composer cs`

2022-12-03 11:05 UTC, jools-r commented
PS: As Textpattern has a forthcoming update (which also incorporates similar fixes for the html5 doctype), it would be brilliant if an updated version of Textile could be part of that.

2022-12-03 13:58 UTC, gocom requested changes

2022-12-03 13:58 UTC, gocom commented on src/Netcarver/Textile/Parser.php
> +        return ($this->getDocumentType() === 'html5') ? '<br>' : '<br />';
Instead of 'html5' string, this could use the self::DOCTYPE_HTML5 constant.

2022-12-03 13:58 UTC, gocom commented on src/Netcarver/Textile/Parser.php
> +        return new Tag($name, $atts, $selfclosing && $this->getDocumentType() !== 'html5');
This could also use the self::DOCTYPE_HTML5 constant instead.

2022-12-03 13:58 UTC, gocom commented on src/Netcarver/Textile/Parser.php
> +    public function getLineBreak()
This should be made protected and `@api` annotation should be removed.

If this is made public and `@api` annotation is used, it becomes part of the public interface and it can never be changed.

2022-12-03 13:58 UTC, gocom commented on src/Netcarver/Textile/Parser.php
> +            if ($this->getDocumentType() === 'xhtml') {
This should use self::DOCTYPE_XHTML constant.

2022-12-03 14:12 UTC, gocom requested changes

2022-12-03 14:12 UTC, gocom commented on src/Netcarver/Textile/Parser.php
> +        $text = preg_replace("~<br[ ]*/?>~i", $this->getLineBreak()."\n", $text);
`preg_replace` here can return `null`, which is causing the static analysis to fail. The result would need to be casted to a string by adding `(string)` here.

2022-12-03 14:15 UTC, gocom commented
Thank you for the PR, jools-r!

I left some review commits and small improvements that could be added to changes before it's merged, and to get the CI to first pass.

2022-12-03 14:24 UTC, gocom requested changes

2022-12-03 15:02 UTC, jools-r commented on src/Netcarver/Textile/Parser.php
> +        return ($this->getDocumentType() === 'html5') ? '<br>' : '<br />';
Thank you for the rapid feedback. Addressed in [573fd14](https://github.com/textile/php-textile/pull/221/commits/573fd1477ee1f8766f6091680f67beb9e6897d54).

2022-12-03 15:03 UTC, jools-r commented on src/Netcarver/Textile/Parser.php
> +        return new Tag($name, $atts, $selfclosing && $this->getDocumentType() !== 'html5');
Addressed in [573fd14](https://github.com/textile/php-textile/pull/221/commits/573fd1477ee1f8766f6091680f67beb9e6897d54).

2022-12-03 15:04 UTC, jools-r commented on src/Netcarver/Textile/Parser.php
> +        $text = preg_replace("~<br[ ]*/?>~i", $this->getLineBreak()."\n", $text);
Addressed in [3f77c76](https://github.com/textile/php-textile/pull/221/commits/3f77c7691e4a13a788246deae0a663d58ed46bf8).

2022-12-03 15:05 UTC, jools-r commented on src/Netcarver/Textile/Parser.php
> +    public function getLineBreak()
Addressed in [ecbc086](https://github.com/textile/php-textile/pull/221/commits/ecbc0869a02f8643d3254d5b843a40afbafda1a1).

2022-12-03 15:31 UTC, gocom requested changes

2022-12-03 15:31 UTC, gocom commented on src/Netcarver/Textile/Parser.php
> +            $block = $whitespace . $this->doPBr($block);
The `$block` string casting that was accidentally removed, would need to be restored here, by adding `(string)` before `$block`. This change is making the static analysis to fail.

2022-12-03 15:48 UTC, jools-r commented on src/Netcarver/Textile/Parser.php
> +        return ($this->getDocumentType() === 'html5') ? '<br>' : '<br />';
This is not something I'm familiar with but I've tried to follow the existing pattern of the fixtures. Three existing fixtures needed the trailing slashes removed for the expected output, and I added two blocks to basic.yaml to specifically test multiline output and images in xhtml and html5 cases. Does that cover it?

As the one new getLineBreak() function is (now) protected, I assume an external test function for that is not necessary?

These are in commit [9d2ed39](https://github.com/textile/php-textile/pull/221/commits/9d2ed396fb1a938b08673b7843c237b37eff197e).

2022-12-03 15:49 UTC, jools-r commented on src/Netcarver/Textile/Parser.php
> +            $block = $whitespace . $this->doPBr($block);
mea culpa. I originally made my changes against the Textpattern repo which has an earlier version without this. [d974eea](https://github.com/textile/php-textile/pull/221/commits/d974eea3d8fae3cbacae39b125b1b194b21e582e) restores the missing `(string)`.

2022-12-03 17:02 UTC, gocom requested changes

2022-12-03 17:02 UTC, gocom commented on src/Netcarver/Textile/Parser.php
> +        $text = (string) preg_replace("~<br[ ]*/?>~i", $this->getLineBreak()."\n", $text);
This change is affecting existing embedded HTML snippets and dividers, by also changing their markup. To avoid this, this line should probably be:

```suggestion
        $text = str_replace($this->getLineBreak(), $this->getLineBreak()."\n", $text);
```

Which would leave user-input markup as-is. PHP-Textile does not change other void tags either, so for consistency you may not want to change br either.

2022-12-03 17:22 UTC, jools-r commented on src/Netcarver/Textile/Parser.php
> +        $text = (string) preg_replace("~<br[ ]*/?>~i", $this->getLineBreak()."\n", $text);
Unfortunately, I don't have a Docker setup for running the unit tests locally. Apologies for imposing on you with each successive small correction. Maybe we are nearly there 😬.

2022-12-03 17:26 UTC, gocom approved these changes

2022-12-03 17:27 UTC, merged

2022-12-03 17:28 UTC, jools-r commented
We did it! Thanks Jukka for your patience in guiding me through the process. I learnt something today.

2022-12-04 09:19 UTC, philwareham commented
Rolled Textile v4 into Textpattern dev branch now for testing. Thanks both!